FROM golang:1.7-alpine

RUN apk add --update bash git ca-certificates jq groff git tree make
RUN go get github.com/LK4D4/vndr

ENV USER root
WORKDIR /go/src/loadbalancer/vendor/github.com/docker/editions/pkg/loadbalancer
COPY pkg/loadbalancer ./
WORKDIR /go/src/loadbalancer
COPY azure/dockerfiles/alb-controller/files/cmd ./
RUN vndr
RUN mkdir -p /go/bin
RUN go vet
RUN go install

CMD ["ls", "/go/bin/loadbalancer"]
