FROM golang:1.7-alpine

RUN apk add --update bash ca-certificates jq groff git tree make

COPY . /go/src/github.com/docker/editions

ENTRYPOINT cd /go/src/github.com/docker/editions/azure/dockerfiles/files/alb-controller/container && make -k build-in-container
