FROM golang:1.7-alpine

RUN apk add --update git bash
RUN go get github.com/LK4D4/vndr

ENV USER root
WORKDIR /go/
COPY . ./
WORKDIR /go/src/buoy
RUN vndr
WORKDIR /go/

RUN mkdir -p bin

CMD ["./compile.sh"]
