FROM golang:1.7-alpine

RUN apk add --update git bash
RUN go get github.com/LK4D4/vndr

ENV USER root
WORKDIR /go/
COPY . ./
WORKDIR /go/src/buoy
RUN vndr
RUN mkdir -p /go/bin
RUN go vet
RUN go install

CMD ["ls /go/bin/buoy]
