FROM golang:1.7-alpine
MAINTAINER madhu@docker.com

RUN apk add --update git bash
RUN go get github.com/LK4D4/vndr

ENV USER root
WORKDIR /go/
COPY . ./
WORKDIR /go/src/swarm-exec
RUN vndr
RUN mkdir -p /go/bin
RUN go vet
RUN go install -tags netgo

CMD ["ls /go/bin/swarm-exec]
