
# Start infrakit
start : start.sh

# vars - sets the variables
vars : vars.sh

# Configuration for inventory controller
inventory : inventory.yml

# The resource config for entire mystack
vpc : mystack.yml

# The resource config for nodes after phase1
nodes : nodes.yml

# The specific resources we can provision
resources : resources/index.yml

# Create a single instance
ondemand : resources/provision-instance.yml

# Create a spot instance
spot : resources/provision-spot-instance.yml
