{{/* =% text %= */}}

{{ $project := param "project" "string" "project" | prompt "Project?" "string" "myproject" }}

kind: inventory
metadata:
  name: mystack
options:
  ObserveInterval: 5s
  KeySelector: "\\{\\{.Tags.Name\\}\\}"
properties:
  networking:
    - plugin: aws/ec2-vpc
      labels:
        infrakit.scope : {{ $project }}
    - plugin: aws/ec2-internetgateway
      labels:
        infrakit.scope : {{ $project }}
    - plugin: aws/ec2-routetable
      labels:
        infrakit.scope : {{ $project }}
    - plugin: aws/ec2-subnet
      labels:
        infrakit.scope : {{ $project }}
    - plugin: aws/ec2-securitygroup
      labels:
        infrakit.scope : {{ $project }}
  compute:
    - plugin: aws/ec2-instance
      labels:
        infrakit.scope : {{ $project }}
    - plugin: aws/ec2-spot-instance
      labels:
        infrakit.scope : {{ $project }}
