{{/* Input to create a spot instance using the AWS instance plugin */}}
{{/* =% instanceProvision `aws/ec2-spot-instance` %= */}}

{{ $user := param "user" "string" "username" | prompt "Please enter your user name:" "string" (env "USER")}}
{{ $project := param "project" "string" "project" | prompt "Project?" "string" "myproject" }}
{{ $imageId := param "image-id" "string" "Image ID" | prompt "AMI?" "string" "ami-df8406b0" }}
{{ $instanceType := param "instance-type" "string" "instance type" | prompt "Instance type?" "string" "t2.micro" }}

{{ $name := param "name" "string" "Host name" | prompt "Host name?" "string" (cat $project `-` (randAlphaNum 8) | nospace ) }}

{{ $spotPrice := param "spot-price" "string" "Spot price" | prompt "Spot price?" "string" "0.03" }}

{{ $keyName := param "key" "string" "ssh key name" | prompt "SSH key?" "string" "infrakit"}}

{{ $subnet := param "subnet" "string" "subnet" | prompt "Subnet?" "string" "subnet2" }}
{{ $subnetKey := list `inventory` $project `networking/aws/ec2-subnet` (list $project $subnet | join `-`) `Properties` | join `/` }}

{{ $azKey := list $subnetKey `AvailabilityZone` | join `/` }}
{{ $az := metadata $azKey }}

{{ $subnetIdKey := list $subnetKey `SubnetId` | join `/` }}
{{ $subnetId := metadata $subnetIdKey }}

{{ $cidrBlockKey := list $subnetKey `CidrBlock` | join `/` }}
{{ $privateIp := param "private-ip" "string" "IP" | prompt "Private IP address?" "string" (metadata $cidrBlockKey) }}

{{ $securityGroupIdKey := list `inventory` $project `networking/aws/ec2-securitygroup` (list $project `sg1` | join `-`) `Properties/GroupId` | join `/` }}

{{ $securityGroupID := param "security-group-id" "string" "security group id" | prompt "Security group ID?" "string" (metadata $securityGroupIdKey) }}

Tags:
  infrakit_scope: {{ $project }}
  infrakit_created: {{ now | htmlDate }}
  infrakit_user: {{ $user }}

Init: |
  #!/bin/bash
  sudo add-apt-repository ppa:gophers/archive
  sudo apt-get update -y
  sudo apt-get install -y wget curl git golang-1.9-go
  wget -qO- https://get.docker.com | sh
  ln -s /usr/lib/go-1.9/bin/go /usr/local/bin/go

Properties:
  Tags:
    Name: {{ $name }}
    infrakit_user: {{ $user }}
  RequestSpotInstancesInput:
    LaunchSpecification:
      ImageId: {{ $imageId }}
      InstanceType: {{ $instanceType }}
      KeyName: infrakit
      NetworkInterfaces:
      - AssociatePublicIpAddress: true
        DeleteOnTermination: true
        DeviceIndex: 0
        Groups:
        - {{ $securityGroupID }}
        NetworkInterfaceId: null
        PrivateIpAddress: {{ $privateIp  }}
        PrivateIpAddresses: null
        SecondaryPrivateIpAddressCount: null
        SubnetId: {{ $subnetId }}
      Placement:
        AvailabilityZone: {{ $az }}
    SpotPrice: "{{ $spotPrice }}"
    Type: one-time
