{{/* Input to create instance using the AWS instance plugin */}}
{{/* =% instanceProvision `aws/ec2-vpc` %= */}}

{{ $user := param "user" "string" "username" | prompt "Please enter your user name:" "string" (env "USER")}}
{{ $project := param "project" "string" "project" | prompt "Project?" "string" "myproject" }}

{{ $cidr := param "cidr" "string" "CIDR Block" | prompt "CIDR block?" "string" "10.0.0.0/16" }}

Tags:
  infrakit_scope: {{ $project }}
  infrakit_created: {{ now | htmlDate }}
  infrakit_user: {{ $user }}

Properties:
  Tags:
    Name: {{ $project }}-vpc
    infrakit_user: {{ $user }}
  CreateVpcInput:
    CidrBlock: {{ $cidr }}
  ModifyVpcAttributeInputs:
    - EnableDnsSupport :
        Value: true
    - EnableDnsHostnames :
        Value: true
