FROM golang:1.7.4-alpine

RUN apk add --update bash ca-certificates jq git make
ENTRYPOINT cd /go/src/github.com/docker/editions/gcp/dockerfiles/lb-controller && make -k build-in-container

COPY . /go/src/github.com/docker/editions
