FROM golang:1.7-alpine

RUN set -ex \
    && apk add --no-cache --virtual .build-deps \
       gcc libc-dev go git

RUN go get github.com/LK4D4/vndr

WORKDIR /go/
COPY . ./
RUN mkdir -p bin
WORKDIR /go/src/cloudstor

RUN go get cloud.google.com/go/compute/metadata
RUN go get golang.org/x/oauth2/google
RUN go get google.golang.org/api/googleapi
RUN go get google.golang.org/api/compute/v1

RUN vndr
RUN go install --ldflags '-extldflags "-static"'

CMD ["ls", "/go/bin/cloudstor"]
