FROM golang:1.7-alpine

RUN apk add --update --no-cache git
RUN go get -u github.com/LK4D4/vndr
COPY . /go/src/github.com/docker/editions/tools/branchbot
WORKDIR /go/src/github.com/docker/editions/tools/branchbot
RUN vndr
RUN ["go", "install", "github.com/docker/editions/tools/branchbot"]

CMD ["ls", "/go/bin/branchbot"]
