FROM alpine:3.6

MAINTAINER Deep Debroy <ddebroy@docker.com>

RUN apk add --update bash 

ARG TAG_VERSION
ENV TAG=$TAG_VERSION

ADD files/upgrade_wrapper.sh /usr/bin/upgrade_wrapper.sh
RUN chmod 755 /usr/bin/upgrade_wrapper.sh

CMD ["/usr/bin/upgrade_wrapper.sh"]
