FROM alpine:3.5

MAINTAINER French Ben <frenchben@docker.com>

RUN apk add --no-cache --update bash ca-certificates jq groff less nodejs bash python make g++ && \
    npm install -g azure-cli \
    && rm -rf /var/cache/apk/*

RUN azure telemetry --disable
RUN azure config mode arm

# setup init
COPY files/ddc-init/entry.sh /entry.sh
RUN chmod 755 /entry.sh

CMD ["/entry.sh"]
