FROM alpine:3.3

MAINTAINER Ken Cochrane <Ken.Cochrane@Docker.com>

RUN apk add --update bash ca-certificates jq groff less \
    && rm -rf /var/cache/apk/*

# needed in order for go binary to work.
RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

# setup init
RUN mkdir -p /usr/bin/ /var/log/docker/
COPY files/init/entry.sh /entry.sh
ADD files/bin/buoy /usr/bin
RUN chmod 755 /entry.sh /usr/bin/buoy

CMD ["/entry.sh"]
