FROM alpine:edge

MAINTAINER David Chung <david.chung@docker.com>

RUN apk add --no-cache --update --virtual builddeps ca-certificates g++ make python && \
    apk add --no-cache nodejs jq bash && \
    npm install -g azure-cli && \
    apk del builddeps
RUN azure telemetry --disable
RUN azure config mode arm
COPY files/create-sp-azure/create_sp.sh /usr/bin

ENV PROG docker run -ti docker4x/create-sp-azure

ENTRYPOINT [ "create_sp.sh" ]
