baseurl = "http://localhost:8080/"
contentdir = "content"
languageCode = "en-us"
title = "Docker for GCP"
keywords = ["iaas, gcp"]
theme = "hugo-foundation"
canonifyurls = true
relativeURLs = false
#sourceRelativeLinks = true
verbose = true

[blackfriday]
  fractions = false
  smartDashes = false
  plainIDAnchors = true
  gitHubLinkEval = true
  sourceRelativeLinksEval = true
