FROM golang:1.7-alpine

MAINTAINER KenCochrane <Ken.Cochrane@Docker.com>

RUN apk add --update bash ca-certificates jq groff git tree make

RUN mkdir -p /go/src/github.com/docker/editions

ADD ./ /go/src/github.com/docker/editions

ENTRYPOINT cd /go/src/github.com/docker/editions/aws/dockerfiles/files/elb-controller/container && make -k build-in-container




